apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrythx0954.azurecr.io/tripinsights/tripviewer
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile.default.svc.cluster.local"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips.default.svc.cluster.local"
---
kind: Service
apiVersion: v1
metadata:
  name: tripviewer
spec:
  type: ClusterIP
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80