apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  selector:
    matchLabels:
      app: trips
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registrythx0954.azurecr.io/tripinsights/trips
        ports:
        - containerPort: 8080
        env:
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: SQL_PASSWORD
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: SQL_SERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: SQL_DBNAME
---
kind: Service
apiVersion: v1
metadata:
  name: trips
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
