apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-view
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: api-dev@OTAPRD1115ops.onmicrosoft.com
  namespace: web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-edit
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: api-dev@OTAPRD1115ops.onmicrosoft.com
  namespace: api