apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev-view
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: web-dev@otaprd1115ops.onmicrosoft.com
  namespace: api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev-edit
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: web-dev@otaprd1115ops.onmicrosoft.com
  namespace: web