apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openhack-team1

spec:
  rules:
  - host: openhack-team1.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tripviewer
          servicePort: 80